//
// Copyright (C) 1991-1992  id Software
// Copyright (C) 2013  Ioan Chera
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 2 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
//


//
// ORIGINAL WOLFENSTEIN 3-D SPRITES
//
#ifndef SPR_SOD_H_
#define SPR_SOD_H_
enum
{
    SPR_DEMO_sod,
    
    SPR_DEATHCAM_sod,
    SPR_STAT_0_sod,
    SPR_STAT_1_sod,
    SPR_STAT_2_sod,
    SPR_STAT_3_sod,
    SPR_STAT_4_sod,
    SPR_STAT_5_sod,
    SPR_STAT_6_sod,
    SPR_STAT_7_sod,

    SPR_STAT_8_sod,
    SPR_STAT_9_sod,
    SPR_STAT_10_sod,
    SPR_STAT_11_sod,
    SPR_STAT_12_sod,
    SPR_STAT_13_sod,
    SPR_STAT_14_sod,
    SPR_STAT_15_sod,

    SPR_STAT_16_sod,
    SPR_STAT_17_sod,
    SPR_STAT_18_sod,
    SPR_STAT_19_sod,
    SPR_STAT_20_sod,
    SPR_STAT_21_sod,
    SPR_STAT_22_sod,
    SPR_STAT_23_sod,

    SPR_STAT_24_sod,
    SPR_STAT_25_sod,
    SPR_STAT_26_sod,
    SPR_STAT_27_sod,
    SPR_STAT_28_sod,
    SPR_STAT_29_sod,
    SPR_STAT_30_sod,
    SPR_STAT_31_sod,

    SPR_STAT_32_sod,
    SPR_STAT_33_sod,
    SPR_STAT_34_sod,
    SPR_STAT_35_sod,
    SPR_STAT_36_sod,
    SPR_STAT_37_sod,
    SPR_STAT_38_sod,
    SPR_STAT_39_sod,

    SPR_STAT_40_sod,
    SPR_STAT_41_sod,
    SPR_STAT_42_sod,
    SPR_STAT_43_sod,
    SPR_STAT_44_sod,
    SPR_STAT_45_sod,
    SPR_STAT_46_sod,
    SPR_STAT_47_sod,

    SPR_STAT_48_sod,
    SPR_STAT_49_sod,
    SPR_STAT_50_sod,
    SPR_STAT_51_sod,

    SPR_GRD_S_1_sod,
    SPR_GRD_S_2_sod,
    SPR_GRD_S_3_sod,
    SPR_GRD_S_4_sod,
    SPR_GRD_S_5_sod,
    SPR_GRD_S_6_sod,
    SPR_GRD_S_7_sod,
    SPR_GRD_S_8_sod,

    SPR_GRD_W1_1_sod,
    SPR_GRD_W1_2_sod,
    SPR_GRD_W1_3_sod,
    SPR_GRD_W1_4_sod,
    SPR_GRD_W1_5_sod,
    SPR_GRD_W1_6_sod,
    SPR_GRD_W1_7_sod,
    SPR_GRD_W1_8_sod,

    SPR_GRD_W2_1_sod,
    SPR_GRD_W2_2_sod,
    SPR_GRD_W2_3_sod,
    SPR_GRD_W2_4_sod,
    SPR_GRD_W2_5_sod,
    SPR_GRD_W2_6_sod,
    SPR_GRD_W2_7_sod,
    SPR_GRD_W2_8_sod,

    SPR_GRD_W3_1_sod,
    SPR_GRD_W3_2_sod,
    SPR_GRD_W3_3_sod,
    SPR_GRD_W3_4_sod,
    SPR_GRD_W3_5_sod,
    SPR_GRD_W3_6_sod,
    SPR_GRD_W3_7_sod,
    SPR_GRD_W3_8_sod,

    SPR_GRD_W4_1_sod,
    SPR_GRD_W4_2_sod,
    SPR_GRD_W4_3_sod,
    SPR_GRD_W4_4_sod,
    SPR_GRD_W4_5_sod,
    SPR_GRD_W4_6_sod,
    SPR_GRD_W4_7_sod,
    SPR_GRD_W4_8_sod,

    SPR_GRD_PAIN_1_sod,
    SPR_GRD_DIE_1_sod,
    SPR_GRD_DIE_2_sod,
    SPR_GRD_DIE_3_sod,
    SPR_GRD_PAIN_2_sod,
    SPR_GRD_DEAD_sod,

    SPR_GRD_SHOOT1_sod,
    SPR_GRD_SHOOT2_sod,
    SPR_GRD_SHOOT3_sod,

    SPR_DOG_W1_1_sod,
    SPR_DOG_W1_2_sod,
    SPR_DOG_W1_3_sod,
    SPR_DOG_W1_4_sod,
    SPR_DOG_W1_5_sod,
    SPR_DOG_W1_6_sod,
    SPR_DOG_W1_7_sod,
    SPR_DOG_W1_8_sod,

    SPR_DOG_W2_1_sod,
    SPR_DOG_W2_2_sod,
    SPR_DOG_W2_3_sod,
    SPR_DOG_W2_4_sod,
    SPR_DOG_W2_5_sod,
    SPR_DOG_W2_6_sod,
    SPR_DOG_W2_7_sod,
    SPR_DOG_W2_8_sod,

    SPR_DOG_W3_1_sod,
    SPR_DOG_W3_2_sod,
    SPR_DOG_W3_3_sod,
    SPR_DOG_W3_4_sod,
    SPR_DOG_W3_5_sod,
    SPR_DOG_W3_6_sod,
    SPR_DOG_W3_7_sod,
    SPR_DOG_W3_8_sod,

    SPR_DOG_W4_1_sod,
    SPR_DOG_W4_2_sod,
    SPR_DOG_W4_3_sod,
    SPR_DOG_W4_4_sod,
    SPR_DOG_W4_5_sod,
    SPR_DOG_W4_6_sod,
    SPR_DOG_W4_7_sod,
    SPR_DOG_W4_8_sod,

    SPR_DOG_DIE_1_sod,
    SPR_DOG_DIE_2_sod,
    SPR_DOG_DIE_3_sod,
    SPR_DOG_DEAD_sod,
    SPR_DOG_JUMP1_sod,
    SPR_DOG_JUMP2_sod,
    SPR_DOG_JUMP3_sod,

    SPR_SS_S_1_sod,
    SPR_SS_S_2_sod,
    SPR_SS_S_3_sod,
    SPR_SS_S_4_sod,
    SPR_SS_S_5_sod,
    SPR_SS_S_6_sod,
    SPR_SS_S_7_sod,
    SPR_SS_S_8_sod,

    SPR_SS_W1_1_sod,
    SPR_SS_W1_2_sod,
    SPR_SS_W1_3_sod,
    SPR_SS_W1_4_sod,
    SPR_SS_W1_5_sod,
    SPR_SS_W1_6_sod,
    SPR_SS_W1_7_sod,
    SPR_SS_W1_8_sod,

    SPR_SS_W2_1_sod,
    SPR_SS_W2_2_sod,
    SPR_SS_W2_3_sod,
    SPR_SS_W2_4_sod,
    SPR_SS_W2_5_sod,
    SPR_SS_W2_6_sod,
    SPR_SS_W2_7_sod,
    SPR_SS_W2_8_sod,

    SPR_SS_W3_1_sod,
    SPR_SS_W3_2_sod,
    SPR_SS_W3_3_sod,
    SPR_SS_W3_4_sod,
    SPR_SS_W3_5_sod,
    SPR_SS_W3_6_sod,
    SPR_SS_W3_7_sod,
    SPR_SS_W3_8_sod,

    SPR_SS_W4_1_sod,
    SPR_SS_W4_2_sod,
    SPR_SS_W4_3_sod,
    SPR_SS_W4_4_sod,
    SPR_SS_W4_5_sod,
    SPR_SS_W4_6_sod,
    SPR_SS_W4_7_sod,
    SPR_SS_W4_8_sod,

    SPR_SS_PAIN_1_sod,
    SPR_SS_DIE_1_sod,
    SPR_SS_DIE_2_sod,
    SPR_SS_DIE_3_sod,
    SPR_SS_PAIN_2_sod,
    SPR_SS_DEAD_sod,

    SPR_SS_SHOOT1_sod,
    SPR_SS_SHOOT2_sod,
    SPR_SS_SHOOT3_sod,

    SPR_MUT_S_1_sod,
    SPR_MUT_S_2_sod,
    SPR_MUT_S_3_sod,
    SPR_MUT_S_4_sod,
    SPR_MUT_S_5_sod,
    SPR_MUT_S_6_sod,
    SPR_MUT_S_7_sod,
    SPR_MUT_S_8_sod,

    SPR_MUT_W1_1_sod,
    SPR_MUT_W1_2_sod,
    SPR_MUT_W1_3_sod,
    SPR_MUT_W1_4_sod,
    SPR_MUT_W1_5_sod,
    SPR_MUT_W1_6_sod,
    SPR_MUT_W1_7_sod,
    SPR_MUT_W1_8_sod,

    SPR_MUT_W2_1_sod,
    SPR_MUT_W2_2_sod,
    SPR_MUT_W2_3_sod,
    SPR_MUT_W2_4_sod,
    SPR_MUT_W2_5_sod,
    SPR_MUT_W2_6_sod,
    SPR_MUT_W2_7_sod,
    SPR_MUT_W2_8_sod,

    SPR_MUT_W3_1_sod,
    SPR_MUT_W3_2_sod,
    SPR_MUT_W3_3_sod,
    SPR_MUT_W3_4_sod,
    SPR_MUT_W3_5_sod,
    SPR_MUT_W3_6_sod,
    SPR_MUT_W3_7_sod,
    SPR_MUT_W3_8_sod,

    SPR_MUT_W4_1_sod,
    SPR_MUT_W4_2_sod,
    SPR_MUT_W4_3_sod,
    SPR_MUT_W4_4_sod,
    SPR_MUT_W4_5_sod,
    SPR_MUT_W4_6_sod,
    SPR_MUT_W4_7_sod,
    SPR_MUT_W4_8_sod,

    SPR_MUT_PAIN_1_sod,
    SPR_MUT_DIE_1_sod,
    SPR_MUT_DIE_2_sod,
    SPR_MUT_DIE_3_sod,
    SPR_MUT_PAIN_2_sod,
    SPR_MUT_DIE_4_sod,
    SPR_MUT_DEAD_sod,

    SPR_MUT_SHOOT1_sod,
    SPR_MUT_SHOOT2_sod,
    SPR_MUT_SHOOT3_sod,
    SPR_MUT_SHOOT4_sod,

    SPR_OFC_S_1_sod,
    SPR_OFC_S_2_sod,
    SPR_OFC_S_3_sod,
    SPR_OFC_S_4_sod,
    SPR_OFC_S_5_sod,
    SPR_OFC_S_6_sod,
    SPR_OFC_S_7_sod,
    SPR_OFC_S_8_sod,

    SPR_OFC_W1_1_sod,
    SPR_OFC_W1_2_sod,
    SPR_OFC_W1_3_sod,
    SPR_OFC_W1_4_sod,
    SPR_OFC_W1_5_sod,
    SPR_OFC_W1_6_sod,
    SPR_OFC_W1_7_sod,
    SPR_OFC_W1_8_sod,

    SPR_OFC_W2_1_sod,
    SPR_OFC_W2_2_sod,
    SPR_OFC_W2_3_sod,
    SPR_OFC_W2_4_sod,
    SPR_OFC_W2_5_sod,
    SPR_OFC_W2_6_sod,
    SPR_OFC_W2_7_sod,
    SPR_OFC_W2_8_sod,

    SPR_OFC_W3_1_sod,
    SPR_OFC_W3_2_sod,
    SPR_OFC_W3_3_sod,
    SPR_OFC_W3_4_sod,
    SPR_OFC_W3_5_sod,
    SPR_OFC_W3_6_sod,
    SPR_OFC_W3_7_sod,
    SPR_OFC_W3_8_sod,

    SPR_OFC_W4_1_sod,
    SPR_OFC_W4_2_sod,
    SPR_OFC_W4_3_sod,
    SPR_OFC_W4_4_sod,
    SPR_OFC_W4_5_sod,
    SPR_OFC_W4_6_sod,
    SPR_OFC_W4_7_sod,
    SPR_OFC_W4_8_sod,

    SPR_OFC_PAIN_1_sod,
    SPR_OFC_DIE_1_sod,
    SPR_OFC_DIE_2_sod,
    SPR_OFC_DIE_3_sod,
    SPR_OFC_PAIN_2_sod,
    SPR_OFC_DIE_4_sod,
    SPR_OFC_DEAD_sod,

    SPR_OFC_SHOOT1_sod,
    SPR_OFC_SHOOT2_sod,
    SPR_OFC_SHOOT3_sod,

    SPR_ROCKET_1_sod,
    SPR_ROCKET_2_sod,
    SPR_ROCKET_3_sod,
    SPR_ROCKET_4_sod,
    SPR_ROCKET_5_sod,
    SPR_ROCKET_6_sod,
    SPR_ROCKET_7_sod,
    SPR_ROCKET_8_sod,

    SPR_SMOKE_1_sod,
    SPR_SMOKE_2_sod,
    SPR_SMOKE_3_sod,
    SPR_SMOKE_4_sod,
    SPR_BOOM_1_sod,
    SPR_BOOM_2_sod,
    SPR_BOOM_3_sod,

    SPR_HROCKET_1_sod,
    SPR_HROCKET_2_sod,
    SPR_HROCKET_3_sod,
    SPR_HROCKET_4_sod,
    SPR_HROCKET_5_sod,
    SPR_HROCKET_6_sod,
    SPR_HROCKET_7_sod,
    SPR_HROCKET_8_sod,

    SPR_HSMOKE_1_sod,
    SPR_HSMOKE_2_sod,
    SPR_HSMOKE_3_sod,
    SPR_HSMOKE_4_sod,
    SPR_HBOOM_1_sod,
    SPR_HBOOM_2_sod,
    SPR_HBOOM_3_sod,

    SPR_SPARK1_sod,
    SPR_SPARK2_sod,
    SPR_SPARK3_sod,
    SPR_SPARK4_sod,

    SPR_TRANS_W1_sod,
    SPR_TRANS_W2_sod,
    SPR_TRANS_W3_sod,
    SPR_TRANS_W4_sod,
    SPR_TRANS_SHOOT1_sod,
    SPR_TRANS_SHOOT2_sod,
    SPR_TRANS_SHOOT3_sod,
    SPR_TRANS_DEAD_sod,

    SPR_TRANS_DIE1_sod,
    SPR_TRANS_DIE2_sod,
    SPR_TRANS_DIE3_sod,

    SPR_WILL_W1_sod,
    SPR_WILL_W2_sod,
    SPR_WILL_W3_sod,
    SPR_WILL_W4_sod,
    SPR_WILL_SHOOT1_sod,
    SPR_WILL_SHOOT2_sod,
    SPR_WILL_SHOOT3_sod,
    SPR_WILL_SHOOT4_sod,

    SPR_WILL_DIE1_sod,
    SPR_WILL_DIE2_sod,
    SPR_WILL_DIE3_sod,
    SPR_WILL_DEAD_sod,

    SPR_UBER_W1_sod,
    SPR_UBER_W2_sod,
    SPR_UBER_W3_sod,
    SPR_UBER_W4_sod,
    SPR_UBER_SHOOT1_sod,
    SPR_UBER_SHOOT2_sod,
    SPR_UBER_SHOOT3_sod,
    SPR_UBER_SHOOT4_sod,

    SPR_UBER_DIE1_sod,
    SPR_UBER_DIE2_sod,
    SPR_UBER_DIE3_sod,
    SPR_UBER_DIE4_sod,
    SPR_UBER_DEAD_sod,

    SPR_DEATH_W1_sod,
    SPR_DEATH_W2_sod,
    SPR_DEATH_W3_sod,
    SPR_DEATH_W4_sod,
    SPR_DEATH_SHOOT1_sod,
    SPR_DEATH_SHOOT2_sod,
    SPR_DEATH_SHOOT3_sod,
    SPR_DEATH_SHOOT4_sod,

    SPR_DEATH_DIE1_sod,
    SPR_DEATH_DIE2_sod,
    SPR_DEATH_DIE3_sod,
    SPR_DEATH_DIE4_sod,
    SPR_DEATH_DIE5_sod,
    SPR_DEATH_DIE6_sod,
    SPR_DEATH_DEAD_sod,

    SPR_SPECTRE_W1_sod,
    SPR_SPECTRE_W2_sod,
    SPR_SPECTRE_W3_sod,
    SPR_SPECTRE_W4_sod,
    SPR_SPECTRE_F1_sod,
    SPR_SPECTRE_F2_sod,
    SPR_SPECTRE_F3_sod,
    SPR_SPECTRE_F4_sod,

    SPR_ANGEL_W1_sod,
    SPR_ANGEL_W2_sod,
    SPR_ANGEL_W3_sod,
    SPR_ANGEL_W4_sod,
    SPR_ANGEL_SHOOT1_sod,
    SPR_ANGEL_SHOOT2_sod,
    SPR_ANGEL_TIRED1_sod,
    SPR_ANGEL_TIRED2_sod,

    SPR_ANGEL_DIE1_sod,
    SPR_ANGEL_DIE2_sod,
    SPR_ANGEL_DIE3_sod,
    SPR_ANGEL_DIE4_sod,
    SPR_ANGEL_DIE5_sod,
    SPR_ANGEL_DIE6_sod,
    SPR_ANGEL_DIE7_sod,
    SPR_ANGEL_DEAD_sod,

    SPR_KNIFEREADY_sod,
    SPR_KNIFEATK1_sod,
    SPR_KNIFEATK2_sod,
    SPR_KNIFEATK3_sod,
    SPR_KNIFEATK4_sod,

    SPR_PISTOLREADY_sod,
    SPR_PISTOLATK1_sod,
    SPR_PISTOLATK2_sod,
    SPR_PISTOLATK3_sod,
    SPR_PISTOLATK4_sod,

    SPR_MACHINEGUNREADY_sod,
    SPR_MACHINEGUNATK1_sod,
    SPR_MACHINEGUNATK2_sod,
    MACHINEGUNATK3_sod,
    SPR_MACHINEGUNATK4_sod,

    SPR_CHAINREADY_sod,
    SPR_CHAINATK1_sod,
    SPR_CHAINATK2_sod,
    SPR_CHAINATK3_sod,
    SPR_CHAINATK4_sod,

};
#endif
