name: CI-Build (Linux / Windows / macOS)

on:
  push:
    branches: [ master ]          # build every direct push to master
  pull_request:
    branches: [ master ]          # build any PR whose *target* branch is master
  workflow_dispatch: {}           # manual trigger from the Actions tab

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Ninja
        uses: ashutoshvarma/setup-ninja@v1.1

      - name: Configure
        run: cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

      - name: Build
        run: cmake --build build --config ${{ env.BUILD_TYPE }}

      - name: Install (stage)
        run: cmake --install build --prefix install

      # Upload only when started via “Run workflow” button
      - name: Upload bundle
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: autowolf-${{ runner.os }}-${{ env.BUILD_TYPE }}
          path: install/**
